version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  open-pull-requests-limit: 10
  reviewers:
  - ryz310
  assignees:
  - ryz310
  labels:
  - dependabot
  ignore:
  - dependency-name: simplecov
    versions:
    - ">= 0.19.a, < 0.20"
