require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'pr_comet.gemspec'
    - 'spec/**/*'

RSpec/NestedGroups:
  Max: 4
